export type UUID = string; // format: uuidv4
export type ISODateString = string; // ISO 8601 UTC format, backend stores as date-time format (YYYY-MM-DD HH:MM:SS) while frontend stores as Temporal format for timezone UX handling and normalizes to UTC before sending to backend

export type Country =
  | 'US'
  | 'CA'
  | 'GB'
  | 'DE'
  | 'FR'
  | 'IT'
  | 'ES'
  | 'AU'
  | 'JP'
  | 'CN'
  | 'IN'
  | 'BR'
  | 'MX'
  | 'AR'
  | 'RU'
  | 'KR'
  | 'TH'
  | 'SG'
  | 'HK'
  | 'TW'
  | 'AT'
  | 'BE'
  | 'CH'
  | 'CZ'
  | 'DK'
  | 'FI'
  | 'GR'
  | 'HU'
  | 'IE'
  | 'NL'
  | 'NO'
  | 'PL'
  | 'PT'
  | 'SE'
  | 'SK'
  | 'SI'
  | 'BG'
  | 'HR'
  | 'CY'
  | 'EE'
  | 'LV'
  | 'LT'
  | 'LU'
  | 'MT'
  | 'RO'
  | 'TR'
  | 'IL'
  | 'AE'
  | 'SA'
  | 'ZA'; //Country code (ISO 3166-1 alpha-2)- max length 2 chars

export type Currency = 'USD' | 'EUR' | 'GBP' | 'JPY' | 'AUD' | 'CAD' | 'CHF' | 'CNY' | 'SEK' | 'NZD';

export type PaymentFrequency = 'monthly' | 'quarterly' | 'annually' | 'bullet' | 'interest_only';
export type PaymentStructure = 'monthly_interest_principal_maturity' | 'amortized_interest_principal_maturity';
